default:
	gcc -o prog main.c stringWrap.c input.c listArrayList.c listElem.c mapArrayList.c mapElem.c earthquake.c date.c time.c countryLocation.c countryStatistics.c loaders.c shows.c util.c countstaticShow.c countryEarthquake.c -lm
debug:
	gcc -g -o prog main.c stringWrap.c input.c listArrayList.c listElem.c mapArrayList.c mapElem.c earthquake.c date.c time.c countryLocation.c countryStatistics.c loaders.c shows.c util.c countstaticShow.c countryEarthquake.c -lm
clean:
	rm -f prog